name: Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Apache Maven
      uses: stCarolas/setup-maven@v1
      with:
        maven-version: 3.5.4
    - name: Calculate new version
      id: next_version
      uses: zwaldowski/semver-release-action@v1
      with:
        dry_run: true
        bump: patch
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set new version
      working-directory: enki-core
      run: |
        mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.yml -Doutput=pom.xml
        mvn -q versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -f pom.xml
        mvn -q io.takari.polyglot:polyglot-translate-plugin:translate -Dinput=pom.xml -Doutput=pom.yml
    - name: push
      uses: github-actions-x/commit@v2.1
      working-directory: enki-core
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'bump version'
        force-add: 'true'
        files: pom.yml
